baseURL = "https://mademyday.im/"
languageCode = "en-us"
title = "1Ckpwee"
theme = "hugo-ink"

copyright = "© Enoch Zhao"

# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
paginate = 10 # articles per page

googleAnalytics = ""

[params]
avatar = "https://cdn.jsdelivr.net/gh/1Ckpwee/images@master/blogE743076B-1061-4534-83A5-7C82E71D4527(20230317-092.JPG"
mode = "light"
featherIconsCDN = true
subtitle = "Swim in the edge of the map"
excludedTypes = ["page", "pages"]

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/1Ckpwee"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/ckpwee"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true