baseURL = "https://mademyday.im/"
languageCode = "en-us"
title = "1Ckpwee"
theme = "hugo-ink"

copyright = "© Enoch Zhao"

# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
paginate = 10 # articles per page

googleAnalytics = ""

[params]
avatar = "https://git.poker/1Ckeepw/images/blob/main/20220720/1151658317024_.4sys4t798iw0.webp?raw=true"
mode = "light"
featherIconsCDN = true
subtitle = "Anti-Pattern"
excludedTypes = ["page", "pages"]

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/1Ckpwee"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/ckpwee"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true